linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test

  disable:
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits # I want to use init().
    - godox
    - goerr113 # I want to use dynamic error.
    - gofumpt
    - goimports # False positive with paperswithcode_go.
    - golint
    - gomnd
    - gomoddirectives
    - gosec # hardcoded credential is a false positive
    - interfacer
    - lll # I want to use a long line.
    - maligned
    - nlreturn
    - paralleltest
    - prealloc # is annoying
    - scopelint
    - testpackage
    - varnamelen # I want to use a long variable name.
    - wrapcheck
    - wsl
