linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test

  disable:
    - godox
    - testpackage
    - paralleltest
    - gomnd
    - gochecknoglobals
    - nlreturn
    - exhaustivestruct
    - wsl
    - gofumpt
    - golint
    - scopelint
    - interfacer
    - maligned
    - gomoddirectives
    - wrapcheck
    - funlen
    - goimports # False positive with paperswithcode_go.
    - lll # I want to use a long line.
    - goerr113 # I want to use dynamic error.
    - gochecknoinits # I want to use init().
