coverage:
  status:
    changes:
      default:
        informational: true
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

ignore:
  - "**/*.pb.go"
  - "**/*.pb*.dart"
