apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: pr12er

profiles:
  - name: kkweon-raspberry
    activation:
      - kubeContext: raspberry
    deploy:
      kubectl:
        manifests:
          - k8s/kkweon-raspberry/*.yaml
    build:
      artifacts:
        - image: kkweon/pr12er-server
          context: server
          docker:
            dockerfile: deploy/Dockerfile.raspberry

  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
          - ./k8s/kkweon-okteto/*.yaml

    build:
      artifacts:
        - image: okteto.dev/codingpot-pr12er-server
          context: server
          docker:
            dockerfile: deploy/Dockerfile
