// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/codingpot/pr12er/server/internal/ghv3"
	"github.com/codingpot/pr12er/server/middlewares/metrics"
	"github.com/codingpot/pr12er/server/pkg/env"
	"github.com/codingpot/pr12er/server/pkg/handlers"
	"github.com/codingpot/pr12er/server/pkg/serv"
)

// Injectors from wire.go:

func CreateApplication() *Application {
	config := env.ProvideEnvConfig()
	gitHubV3 := ghv3.ProvideGitHubService(config)
	handler := handlers.ProvideHandler(gitHubV3)
	server := serv.ProvideServer(handler)
	grpcServer := ProvideGRPCServer()
	promServer := metrics.ProvidePrometheusServer(grpcServer, config)
	application := ProvideApplication(config, server, grpcServer, promServer)
	return application
}
