rows:  {
  pr_id:  1
  paper_arxiv_id:  "1406.2661"
  youtube_video_id:  "L3hz57whyNw"
}
rows:  {
  pr_id:  2
  paper_arxiv_id:  "1703.06211"
  youtube_video_id:  "RRwaz0fBQ0Y"
}
rows:  {
  pr_id:  3
  paper_arxiv_id:  "1406.1078"
  youtube_video_id:  "_Dp8u97_rQ0"
}
rows:  {
  pr_id:  4
  paper_arxiv_id:  "1501.00092"
  youtube_video_id:  "1jGr_OFyfa0"
}
rows:  {
  pr_id:  5
  paper_arxiv_id:  "1312.5602"
  youtube_video_id:  "V7_cNTfm2i8"
}
rows:  {
  pr_id:  6
  paper_arxiv_id:  "1410.5401"
  youtube_video_id:  "2wbDiZCWQtY"
}
rows:  {
  pr_id:  7
  paper_arxiv_id:  "1703.07511"
  youtube_video_id:  "YF6nLVDlznE"
}
rows:  {
  pr_id:  8
  paper_arxiv_id:  "1702.03407"
  youtube_video_id:  "jbnjzyJDldA"
}
rows:  {
  pr_id:  9
  paper_arxiv_id:  "1503.02531"
  youtube_video_id:  "tOItokBZSfU"
}
rows:  {
  pr_id:  10
  paper_arxiv_id:  "1312.6114"
  youtube_video_id:  "KYA-GEhObIs"
}
rows:  {
  pr_id:  11
  paper_arxiv_id:  "1506.02025"
  youtube_video_id:  "Rv3osRZWGbg"
}
rows:  {
  pr_id:  12
  paper_arxiv_id:  "1506.01497"
  youtube_video_id:  "kcPAGIgBGRs"
}
rows:  {
  pr_id:  13
  paper_arxiv_id:  "1505.07818"
  youtube_video_id:  "n2J7giHrS-Y"
}
rows:  {
  pr_id:  14
  paper_arxiv_id:  "1705.02445"
  youtube_video_id:  "Y1loN3Sc4Dk"
}
rows:  {
  pr_id:  15
  paper_arxiv_id:  "1408.5882"
  youtube_video_id:  "IRB2vXSet2E"
}
rows:  {
  pr_id:  16
  paper_arxiv_id:  "1506.02640"
  youtube_video_id:  "eTDcoeqj1_w"
}
rows:  {
  pr_id:  17
  paper_arxiv_id:  "1611.01578"
  youtube_video_id:  "XP3vyVrrt3Q"
}
rows:  {
  pr_id:  18
  paper_arxiv_id:  "1706.01427"
  youtube_video_id:  "Lb1PVpFp9F8"
}
rows:  {
  pr_id:  19
  paper_arxiv_id:  "1509.02971"
  youtube_video_id:  "h2WSVBAC1t4"
}
rows:  {
  pr_id:  20
  paper_arxiv_id:  "1502.01852"
  youtube_video_id:  "absOinFeGv0"
}
rows:  {
  pr_id:  21
  paper_arxiv_id:  "1502.03167"
  youtube_video_id:  "TDx8iZHwFtM"
}
rows:  {
  pr_id:  22
  paper_arxiv_id:  "1606.03657"
  youtube_video_id:  "_4jbgniqt_Q"
}
rows:  {
  pr_id:  23
  paper_arxiv_id:  "1612.08242"
  youtube_video_id:  "6fdclSGgeio"
}
rows:  {
  pr_id:  24
  paper_arxiv_id:  "1601.06759"
  youtube_video_id:  "BvcwEz4VPIQ"
}
rows:  {
  pr_id:  25
  paper_arxiv_id:  "1908.10559"
  youtube_video_id:  "KdRo7ATNs9g"
}
rows:  {
  pr_id:  26
  paper_arxiv_id:  "1505.04597"
  youtube_video_id:  "ZdPBkPGfRSk"
}
rows:  {
  pr_id:  27
  paper_arxiv_id:  "1411.5595"
  youtube_video_id:  "uZ2GtEe-50E"
}
rows:  {
  pr_id:  28
  paper_arxiv_id:  "1608.06993"
  youtube_video_id:  "fe2Vn0mwALI"
}
rows:  {
  pr_id:  29
  paper_arxiv_id:  "1206.5264"
  youtube_video_id:  "AXi4s3aFN6M"
}
rows:  {
  pr_id:  30
  paper_arxiv_id:  "1609.04802"
  youtube_video_id:  "nGPMKnoJTcI"
}
rows:  {
  pr_id:  31
  paper_arxiv_id:  "1606.04474"
  youtube_video_id:  "p55H46RiZ6k"
}
rows:  {
  pr_id:  32
  paper_arxiv_id:  "1412.2306"
  youtube_video_id:  "Q-Cm7nw85iE"
}
rows:  {
  pr_id:  33
  paper_arxiv_id:  "1611.08588"
  youtube_video_id:  "TYDGTnxUGHQ"
}
rows:  {
  pr_id:  34
  paper_arxiv_id:  "1610.02357"
  youtube_video_id:  "V0dLhyg5_Dw"
}
rows:  {
  pr_id:  35
  paper_arxiv_id:  "1703.04730"
  youtube_video_id:  "xlmlY8WHjkU"
}
rows:  {
  pr_id:  36
  paper_arxiv_id:  "1703.03129"
  youtube_video_id:  "S_fbBYbXypc"
}
rows:  {
  pr_id:  37
  paper_arxiv_id:  "1506.07285"
  youtube_video_id:  "oxSrjuspQEs"
}
rows:  {
  pr_id:  38
  paper_arxiv_id:  "1412.6572"
  youtube_video_id:  "7hRO2bS810M"
}
rows:  {
  pr_id:  39
  paper_arxiv_id:  "1506.02142"
  youtube_video_id:  "aU91bDGmy7I"
}
rows:  {
  pr_id:  40
  paper_arxiv_id:  "1609.03499"
  youtube_video_id:  "GyQnex_DK2k"
}
rows:  {
  pr_id:  41
  paper_arxiv_id:  "1411.4555"
  youtube_video_id:  "BrmCnoYhQb4"
}
rows:  {
  pr_id:  42
  paper_arxiv_id:  "1412.6980"
  youtube_video_id:  "KN120w3PZIA"
}
rows:  {
  pr_id:  43
  paper_arxiv_id:  "1609.09106"
  youtube_video_id:  "-tUQXSdEsMk"
}
rows:  {
  pr_id:  44
  paper_arxiv_id:  "1704.04861"
  youtube_video_id:  "7UoOFKcyIvM"
}
rows:  {
  pr_id:  45
  paper_arxiv_id:  "1606.00915"
  youtube_video_id:  "JiC78rUF4iI"
}
rows:  {
  pr_id:  46
  paper_arxiv_id:  "1506.05908"
  youtube_video_id:  "8hdY6Jns5-k"
}
rows:  {
  pr_id:  47
  paper_arxiv_id:  "1512.04150"
  youtube_video_id:  "-Z1NIzLxgRU"
}
rows:  {
  pr_id:  48
  paper_arxiv_id:  "1701.04862"
  youtube_video_id:  "RlAgB0Ooxaw"
}
rows:  {
  pr_id:  49
  paper_arxiv_id:  "1706.03762"
  youtube_video_id:  "6zGgVIlStXs"
}
rows:  {
  pr_id:  50
  paper_arxiv_id:  "1506.04214"
  youtube_video_id:  "3cFfCM4CXws"
}
rows:  {
  pr_id:  51
  paper_arxiv_id:  "1411.1784"
  youtube_video_id:  "iCgT8G4PkqI"
}
rows:  {
  pr_id:  52
  paper_arxiv_id:  "1910.13012"
}
rows:  {
  pr_id:  53
  paper_arxiv_id:  "1610.02391"
  youtube_video_id:  "faGsrPX1yFM"
}
rows:  {
  pr_id:  54
  paper_arxiv_id:  "1707.01083"
  youtube_video_id:  "pNuBdj53Hbc"
}
rows:  {
  pr_id:  55
  paper_arxiv_id:  "1409.0473"
  youtube_video_id:  "upskBSbA9cA"
}
rows:  {
  pr_id:  56
  paper_arxiv_id:  "1710.09829"
  youtube_video_id:  "_YT_8CT2w_Q"
}
rows:  {
  pr_id:  57
  paper_arxiv_id:  "1703.06870"
  youtube_video_id:  "RtSZALC9DlU"
}
rows:  {
  pr_id:  58
  paper_arxiv_id:  "1709.08568"
  youtube_video_id:  "7fIAdhl0KYc"
}
rows:  {
  pr_id:  59
  paper_arxiv_id:  "1705.09655"
  youtube_video_id:  "w-P2V2LlrHg"
}
rows:  {
  pr_id:  60
  paper_arxiv_id:  "1707.07435"
  youtube_video_id:  "V6zixdCIOqw"
}
rows:  {
  pr_id:  61
  paper_arxiv_id:  "1611.03530"
  youtube_video_id:  "UxJNG7ENRNg"
}
rows:  {
  pr_id:  62
  paper_arxiv_id:  "1801.00631"
  youtube_video_id:  "6hg5d10SZr0"
}
rows:  {
  pr_id:  63
  paper_arxiv_id:  "1712.03351"
  youtube_video_id:  "ZO4bXgdcCQA"
}
rows:  {
  pr_id:  64
  paper_arxiv_id:  "1606.07792"
  youtube_video_id:  "hKoJPqWLrI4"
}
rows:  {
  pr_id:  65
  paper_arxiv_id:  "1711.11585"
  youtube_video_id:  "_5ofbwltEKU"
}
rows:  {
  pr_id:  66
  paper_arxiv_id:  "1711.00489"
  youtube_video_id:  "jFpO-E4RPhQ"
}
rows:  {
  pr_id:  67
  paper_arxiv_id:  "1708.00853"
  youtube_video_id:  "iqN08EPMjSs"
}
rows:  {
  pr_id:  68
  paper_arxiv_id:  "1704.04110"
  youtube_video_id:  "okyo61ZZivA"
}
rows:  {
  pr_id:  69
  paper_arxiv_id:  "1802.03268"
  youtube_video_id:  "fbCcJaSQPPA"
}
rows:  {
  pr_id:  70
  paper_arxiv_id:  "1706.10268"
  youtube_video_id:  "CtaPFqq8P00"
}
rows:  {
  pr_id:  71
  paper_arxiv_id:  "1611.01144"
  youtube_video_id:  "ty3SciyoIyk"
}
rows:  {
  pr_id:  72
  paper_arxiv_id:  "1510.00149"
  youtube_video_id:  "9mFZmpIbMDs"
}
rows:  {
  pr_id:  73
  paper_arxiv_id:  "1708.00315"
  youtube_video_id:  "U8IpNf1b57w"
}
rows:  {
  pr_id:  74
  paper_arxiv_id:  "1801.01442"
  youtube_video_id:  "A1o6SUsWd98"
}
rows:  {
  pr_id:  75
  paper_arxiv_id:  "1706.04599"
  youtube_video_id:  "odNHEkfJAc4"
}
rows:  {
  pr_id:  76
  paper_arxiv_id:  "1405.4053"
  youtube_video_id:  "NxKpgY6sWOQ"
}
rows:  {
  pr_id:  77
  paper_arxiv_id:  "1609.05473"
  youtube_video_id:  "BXODIP3QjJI"
}
rows:  {
  pr_id:  78
  paper_arxiv_id:  "1511.05641"
  youtube_video_id:  "btsZOMsyH_o"
}
rows:  {
  pr_id:  79
  paper_arxiv_id:  "1802.04208"
  youtube_video_id:  "UXVKSSXdwb8"
}
rows:  {
  pr_id:  80
  paper_arxiv_id:  "1206.2944"
  youtube_video_id:  "MnHCe8tGjQ8"
}
rows:  {
  pr_id:  81
  paper_arxiv_id:  "1802.07740"
}
rows:  {
  pr_id:  82
  paper_arxiv_id:  "1708.07524"
  youtube_video_id:  "OgNSFKeHy8k"
}
rows:  {
  pr_id:  83
  paper_arxiv_id:  "1711.07971"
  youtube_video_id:  "ZM153wo3baA"
}
rows:  {
  pr_id:  84
  paper_arxiv_id:  "1711.07240"
  youtube_video_id:  "nkYFEoKQBH0"
}
rows:  {
  pr_id:  85
  paper_arxiv_id:  "1704.04760"
  youtube_video_id:  "7WhWkhFAIO4"
}
rows:  {
  pr_id:  86
  paper_arxiv_id:  "1904.03626"
  youtube_video_id:  "fQtuWEuwXrA"
}
rows:  {
  pr_id:  87
  paper_arxiv_id:  "1802.05957"
  youtube_video_id:  "iXSYqohGQhM"
}
rows:  {
  pr_id:  88
  paper_arxiv_id:  "1605.06432"
  youtube_video_id:  "uM0rQtL6_AA"
}
rows:  {
  pr_id:  89
  paper_arxiv_id:  "1801.05453"
  youtube_video_id:  "5whGIpoLoq4"
}
rows:  {
  pr_id:  90
  paper_arxiv_id:  "1708.06734"
  youtube_video_id:  "T7i_YKN2EY8"
}
rows:  {
  pr_id:  91
  paper_arxiv_id:  "null"
  youtube_video_id:  "v1GbxpKqH8Q"
}
rows:  {
  pr_id:  92
  paper_arxiv_id:  "1810.11787"
  youtube_video_id:  "pAH3KhVnADE"
}
rows:  {
  pr_id:  93
  paper_arxiv_id:  "1805.11592"
}
rows:  {
  pr_id:  94
  paper_arxiv_id:  "1703.03400"
  youtube_video_id:  "fxJXXKZb-ik"
}
rows:  {
  pr_id:  95
  paper_arxiv_id:  "1806.06765"
  youtube_video_id:  "dAGI3mlOmfw"
}
rows:  {
  pr_id:  96
  paper_arxiv_id:  "1804.08328"
  youtube_video_id:  "WjUGrzBIDv0"
}
rows:  {
  pr_id:  97
  paper_arxiv_id:  "1605.03661"
  youtube_video_id:  "l-pcG77Hr58"
}
rows:  {
  pr_id:  98
  paper_arxiv_id:  "1804.00607"
  youtube_video_id:  "tGbMWAFMMBQ"
}
rows:  {
  pr_id:  99
  paper_arxiv_id:  "1709.07534"
  youtube_video_id:  "cpCS7LBRkRU"
}
rows:  {
  pr_id:  100
  paper_arxiv_id:  "2001.10331"
  youtube_video_id:  "ksTkCecBTCY"
}
rows:  {
  pr_id:  101
  paper_arxiv_id:  "1610.00291"
  youtube_video_id:  "FfBp6xJqZVA"
}
rows:  {
  pr_id:  102
  paper_arxiv_id:  "1808.07371"
  youtube_video_id:  "_onRnCb_h3Q"
}
rows:  {
  pr_id:  103
  paper_arxiv_id:  "1803.01768"
  youtube_video_id:  "zpJwm7f7EXs"
}
rows:  {
  pr_id:  104
  paper_arxiv_id:  "1808.06601"
  youtube_video_id:  "WxeeqxqnRyE"
}
rows:  {
  pr_id:  105
  paper_arxiv_id:  "1807.11626"
  youtube_video_id:  "4uDZxefPd-I"
}
rows:  {
  pr_id:  106
  paper_arxiv_id:  "1802.07814"
  youtube_video_id:  "id_CmUaTWpg"
}
rows:  {
  pr_id:  107
  paper_arxiv_id:  "1804.07723"
  youtube_video_id:  "BhZN6AqfylA"
}
rows:  {
  pr_id:  108
  paper_arxiv_id:  "1801.04381"
  youtube_video_id:  "mT5Y-Zumbbw"
}
rows:  {
  pr_id:  109
  paper_arxiv_id:  "1809.11096"
  youtube_video_id:  "1f0faOeqDQ0"
}
rows:  {
  pr_id:  110
  paper_arxiv_id:  "1711.08189"
  youtube_video_id:  "nimHWHxjBJ8"
}
rows:  {
  pr_id:  111
  paper_arxiv_id:  "1803.06312"
  youtube_video_id:  "uwRz7PjVtB0"
}
rows:  {
  pr_id:  112
  paper_arxiv_id:  "1404.2986"
  youtube_video_id:  "mLSPA76qSuU"
}
rows:  {
  pr_id:  113
  paper_arxiv_id:  "1711.06077"
  youtube_video_id:  "6Yid4dituqo"
}
rows:  {
  pr_id:  114
  paper_arxiv_id:  "1808.05174"
  youtube_video_id:  "eMZXUqmp_PU"
}
rows:  {
  pr_id:  115
  paper_arxiv_id:  "1703.05921"
  youtube_video_id:  "R0H0gqtnMyA"
}
rows:  {
  pr_id:  116
  paper_arxiv_id:  "1807.03039"
  youtube_video_id:  "6OVH1i2BVAE"
}
rows:  {
  pr_id:  117
  paper_arxiv_id:  "1806.00088"
  youtube_video_id:  "VQsG_Yk9KuQ"
}
rows:  {
  pr_id:  118
  paper_arxiv_id:  "1804.08598"
  youtube_video_id:  "AMPpOFtg3Q4"
}
rows:  {
  pr_id:  119
  paper_arxiv_id:  "1708.00489"
  youtube_video_id:  "3ROQis3hxPs"
}
rows:  {
  pr_id:  120
  paper_arxiv_id:  "1807.11164"
  youtube_video_id:  "lrU6uXiJ_9Y"
}
rows:  {
  pr_id:  121
  paper_arxiv_id:  "1810.04805"
  youtube_video_id:  "GK4IO3qOnLc"
}
rows:  {
  pr_id:  122
  paper_arxiv_id:  "1706.07068"
  youtube_video_id:  "TB7izZIWYyw"
}
rows:  {
  pr_id:  123
  paper_arxiv_id:  "1811.11718"
  youtube_video_id:  "IKHzc7sGCxQ"
}
rows:  {
  pr_id:  124
  paper_arxiv_id:  "2102.08012"
  youtube_video_id:  "saJcr74ldvs"
}
rows:  {
  pr_id:  125
  paper_arxiv_id:  "1609.03126"
  youtube_video_id:  "8PoewOpK6b4"
}
rows:  {
  pr_id:  126
  paper_arxiv_id:  "1802.00434"
  youtube_video_id:  "-bvMCbk_FT8"
}
rows:  {
  pr_id:  127
  paper_arxiv_id:  "1503.03832"
  youtube_video_id:  "0k3X-9y_9S8"
}
rows:  {
  pr_id:  128
  paper_arxiv_id:  "1811.09620"
  youtube_video_id:  "5eofa6SksKU"
}
rows:  {
  pr_id:  129
  paper_arxiv_id:  "1802.05799"
  youtube_video_id:  "8zQECRiONAo"
}
rows:  {
  pr_id:  130
  paper_arxiv_id:  "1606.03476"
  youtube_video_id:  "XHmRsgFrCTM"
}
rows:  {
  pr_id:  131
  paper_arxiv_id:  "1812.04948"
  youtube_video_id:  "TWzEbMrH59o"
}
rows:  {
  pr_id:  132
  paper_arxiv_id:  "1512.02325"
  youtube_video_id:  "ej1ISEoAK5g"
}
rows:  {
  pr_id:  133
  paper_arxiv_id:  "1706.02677"
  youtube_video_id:  "g3McZgloCJo"
}
rows:  {
  pr_id:  134
  paper_arxiv_id:  "1805.11604"
  youtube_video_id:  "hiN0IMM50FM"
}
rows:  {
  pr_id:  135
  paper_arxiv_id:  "1812.02246"
  youtube_video_id:  "LSlBoNNbULg"
}
rows:  {
  pr_id:  136
  paper_arxiv_id:  "1811.11212"
  youtube_video_id:  "_wpDP-6afM4"
}
rows:  {
  pr_id:  137
  paper_arxiv_id:  "1801.04062"
}
rows:  {
  pr_id:  138
  paper_arxiv_id:  "1906.03631"
  youtube_video_id:  "VORJQQUphuw"
}
rows:  {
  pr_id:  139
  paper_arxiv_id:  "1606.09549"
  youtube_video_id:  "dv5yUl6Lw1g"
}
rows:  {
  pr_id:  140
  paper_arxiv_id:  "1801.08019"
  youtube_video_id:  "_2l2UFIF08Q"
}
rows:  {
  pr_id:  141
  paper_arxiv_id:  "1901.02985"
  youtube_video_id:  "ltlhQXHGzgE"
}
rows:  {
  pr_id:  142
  paper_arxiv_id:  "1701.07875"
  youtube_video_id:  "tKQwlf-DAl0"
}
rows:  {
  pr_id:  143
  paper_arxiv_id:  "1809.01999"
  youtube_video_id:  "APjGjwBR6o8"
}
rows:  {
  pr_id:  144
  paper_arxiv_id:  "1803.10615"
  youtube_video_id:  "WReWeADJ3Pw"
}
rows:  {
  pr_id:  145
  paper_arxiv_id:  "1904.02679"
  youtube_video_id:  "f5zULULWUwM"
}
rows:  {
  pr_id:  146
  paper_arxiv_id:  "1808.01244"
  youtube_video_id:  "6OYmOtivQY8"
}
rows:  {
  pr_id:  147
  paper_arxiv_id:  "1511.06078"
  youtube_video_id:  "7lyxexSjshc"
}
rows:  {
  pr_id:  148
  paper_arxiv_id:  "1805.10917"
  youtube_video_id:  "TgJuUxtLO3s"
}
rows:  {
  pr_id:  149
  paper_arxiv_id:  "1603.08155"
  youtube_video_id:  "OKDaGzeUz4U"
}
rows:  {
  pr_id:  150
  paper_arxiv_id:  "1811.12231"
  youtube_video_id:  "oBapZTL8LsE"
}
rows:  {
  pr_id:  151
  paper_arxiv_id:  "1801.03924"
  youtube_video_id:  "VDeJFb5jt5M"
}
rows:  {
  pr_id:  152
  paper_arxiv_id:  "1711.09020"
  youtube_video_id:  "i3-rTEFpyv0"
}
rows:  {
  pr_id:  153
  paper_arxiv_id:  "1707.03141"
  youtube_video_id:  "zGrwpa5-_0Y"
}
rows:  {
  pr_id:  154
  paper_arxiv_id:  "1903.07291"
  youtube_video_id:  "1nJf35TSYtE"
}
rows:  {
  pr_id:  155
  paper_arxiv_id:  "1904.01569"
  youtube_video_id:  "qnGm1h365tc"
}
rows:  {
  pr_id:  156
  paper_arxiv_id:  "1809.01330"
  youtube_video_id:  "oZbKWOBfNhk"
}
rows:  {
  pr_id:  157
  paper_arxiv_id:  "1806.07527"
  youtube_video_id:  "JbXdn44myP4"
}
rows:  {
  pr_id:  158
  paper_arxiv_id:  "1801.01671"
  youtube_video_id:  "hOFViMbYnrs"
}
rows:  {
  pr_id:  159
  paper_arxiv_id:  "1901.08211"
  youtube_video_id:  "sR7hBJGpwQo"
}
rows:  {
  pr_id:  160
  paper_arxiv_id:  "1806.05662"
  youtube_video_id:  "V9KusGzsx10"
}
rows:  {
  pr_id:  161
  paper_arxiv_id:  "1901.02860"
  youtube_video_id:  "lSTljZy8ag4"
}
rows:  {
  pr_id:  162
  paper_arxiv_id:  "1704.02729"
  youtube_video_id:  "AqStpR29lTA"
}
rows:  {
  pr_id:  163
  paper_arxiv_id:  "2006.14135"
  youtube_video_id:  "Dvi5_YC8Yts"
}
rows:  {
  pr_id:  164
  paper_arxiv_id:  "1706.02262"
  youtube_video_id:  "29QcXLoYC60"
}
rows:  {
  pr_id:  165
  paper_arxiv_id:  "1905.08233"
  youtube_video_id:  "4pY_6VG4npc"
}
rows:  {
  pr_id:  166
  paper_arxiv_id:  "1904.07392"
  youtube_video_id:  "FAAt0jejWOA"
}
rows:  {
  pr_id:  167
  paper_arxiv_id:  "1711.11279"
  youtube_video_id:  "-y0oghbEHMM"
}
rows:  {
  pr_id:  168
  paper_arxiv_id:  "1905.01723"
  youtube_video_id:  "ANwAhuOeaiE"
}
rows:  {
  pr_id:  169
  paper_arxiv_id:  "1905.11946"
  youtube_video_id:  "Vhz0quyvR7I"
}
rows:  {
  pr_id:  170
  paper_arxiv_id:  "1512.03385"
  youtube_video_id:  "7fSgqlC7Wdo"
}
rows:  {
  pr_id:  171
  paper_arxiv_id:  "1612.02295"
  youtube_video_id:  "7TugLIfExKM"
}
rows:  {
  pr_id:  172
  paper_arxiv_id:  "1902.09630"
  youtube_video_id:  "ENZBhDx0kqM"
}
rows:  {
  pr_id:  173
  paper_arxiv_id:  "1610.02415"
  youtube_video_id:  "hk4e8ZCkNWg"
}
rows:  {
  pr_id:  174
  paper_arxiv_id:  "1005.1593"
  youtube_video_id:  "yqFDyX4ErSI"
}
rows:  {
  pr_id:  175
  paper_arxiv_id:  "1906.08237"
  youtube_video_id:  "koj9BKiu1rU"
}
rows:  {
  pr_id:  176
  paper_arxiv_id:  "1905.10964"
  youtube_video_id:  "ihbEF6WGlrA"
}
rows:  {
  pr_id:  177
  paper_arxiv_id:  "1708.08333"
  youtube_video_id:  "KSJcQlEKI0Q"
}
rows:  {
  pr_id:  178
  paper_arxiv_id:  "1609.02907"
  youtube_video_id:  "uqBsvoOY8jM"
}
rows:  {
  pr_id:  179
  paper_arxiv_id:  "1907.04378"
  youtube_video_id:  "CpRGaFPIZnw"
}
rows:  {
  pr_id:  180
  paper_arxiv_id:  "1803.03635"
  youtube_video_id:  "dkNmYu610r8"
}
rows:  {
  pr_id:  181
  paper_arxiv_id:  "1904.02868"
  youtube_video_id:  "YdCXbBDuVuE"
}
rows:  {
  pr_id:  182
  paper_arxiv_id:  "2104.02395"
  youtube_video_id:  "twhZ3j_VCa0"
}
rows:  {
  pr_id:  183
  paper_arxiv_id:  "1907.09595"
  youtube_video_id:  "252YxqpHzsg"
}
rows:  {
  pr_id:  184
  paper_arxiv_id:  "1907.05686"
  youtube_video_id:  "FPLvzxH8geY"
}
rows:  {
  pr_id:  185
  paper_arxiv_id:  "1905.00641"
  youtube_video_id:  "DkcHEnxkXpM"
}
rows:  {
  pr_id:  186
  paper_arxiv_id:  "1703.06868"
  youtube_video_id:  "16BGnsIyh6M"
}
rows:  {
  pr_id:  187
  paper_arxiv_id:  "1711.06798"
  youtube_video_id:  "vUNAJsO2G98"
}
rows:  {
  pr_id:  188
  paper_arxiv_id:  "1902.08438"
  youtube_video_id:  "vUNAJsO2G98"
}
rows:  {
  pr_id:  189
  paper_arxiv_id:  "1904.12848"
  youtube_video_id:  "YiKn93Ud4dA"
}
rows:  {
  pr_id:  190
  paper_arxiv_id:  "1610.02136"
  youtube_video_id:  "xaABseUoHAI"
}
rows:  {
  pr_id:  191
  paper_arxiv_id:  "1802.06309"
  youtube_video_id:  "cgolskL-_WM"
}
rows:  {
  pr_id:  192
  paper_arxiv_id:  "1707.04993"
  youtube_video_id:  "9uNFtnRa_JU"
}
rows:  {
  pr_id:  193
  paper_arxiv_id:  "1711.05908"
  youtube_video_id:  "3KoqN_yYhmI"
}
rows:  {
  pr_id:  194
  paper_arxiv_id:  "1908.09791"
}
rows:  {
  pr_id:  195
  paper_arxiv_id:  "1905.02249"
  youtube_video_id:  "ud863JQmUW0"
}
rows:  {
  pr_id:  196
  paper_arxiv_id:  "1906.05909"
  youtube_video_id:  "6hadVw4Sy2M"
}
rows:  {
  pr_id:  197
  paper_arxiv_id:  "1906.02773"
  youtube_video_id:  "YmTNpF2OOjA"
}
rows:  {
  pr_id:  198
  paper_arxiv_id:  "1811.08383"
}
rows:  {
  pr_id:  199
  paper_arxiv_id:  "1805.09300"
  youtube_video_id:  "EkndN7svgUk"
}
rows:  {
  pr_id:  200
  paper_arxiv_id:  "1812.02699"
  youtube_video_id:  "BHEncY-f548"
}
rows:  {
  pr_id:  201
  paper_arxiv_id:  "1812.01187"
  youtube_video_id:  "D-baIgejA4M"
}
rows:  {
  pr_id:  202
  paper_arxiv_id:  "1806.01531"
  youtube_video_id:  "iR7T3lH20gI"
}
rows:  {
  pr_id:  203
  paper_arxiv_id:  "1901.05555"
  youtube_video_id:  "3hL0uVtJrXM"
}
rows:  {
  pr_id:  204
  paper_arxiv_id:  "1808.06670"
  youtube_video_id:  "YNicvevmByo"
}
rows:  {
  pr_id:  205
  paper_arxiv_id:  "1904.04232"
  youtube_video_id:  "yyqZ1K5u2_8"
}
rows:  {
  pr_id:  206
  paper_arxiv_id:  "1812.04244"
  youtube_video_id:  "sFN_EgCsNzM"
}
rows:  {
  pr_id:  207
  paper_arxiv_id:  "1804.02767"
  youtube_video_id:  "HMgcvgRrDcA"
}
