kind: ConfigMap
metadata:
  name: grafana-agent
apiVersion: v1
data:
  agent.yaml: |
    server:
      http_listen_port: 12345
      http_path_prefix: /grafana-agent/
    prometheus:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: ${GRAFANA_KKWEON_USERNAME}
            password: ${GRAFANA_KKWEON_PASSWORD}
        scrape_configs:
        - job_name: integrations/kubernetes/services
          static_configs:
            - targets:
              - server:9093
    integrations:
      prometheus_remote_write:
      - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: ${GRAFANA_KKWEON_USERNAME}
          password: ${GRAFANA_KKWEON_PASSWORD}

    loki:
      configs:
      - name: integrations
        clients:
        - url: https://logs-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: ${GRAFANA_KKWEON_USERNAME}
            password: ${GRAFANA_KKWEON_PASSWORD}
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-agent
  name: grafana-agent
spec:
  ports:
    - name: http-metrics
      port: 12345
      targetPort: http-metrics
  selector:
    app: grafana-agent
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-agent
  name: grafana-agent
  namespace: kkweon
spec:
  minReadySeconds: 10
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
          command:
            - /bin/agent
          image: grafana/agent:v0.15.0
          imagePullPolicy: IfNotPresent
          name: agent
          ports:
            - containerPort: 12345
              name: http-metrics
          volumeMounts:
            - mountPath: /etc/agent
              name: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent
          name: grafana-agent