pr_id_to_video:  {
  key:  1
  value:  {
    video:  {
      video_id:  "L3hz57whyNw"
      video_title:  "PR-001: Generative adversarial nets by Jaejun Yoo (2017/4/13)"
      number_of_likes:  255
      number_of_views:  34414
      published_date:  {
        seconds:  1492839397
      }
      uploader:  "Sung Kim"
    }
  }
}
pr_id_to_video:  {
  key:  2
  value:  {
    video:  {
      video_id:  "RRwaz0fBQ0Y"
      video_title:  "PR-002: Deformable Convolutional Networks (2017)"
      number_of_likes:  110
      number_of_views:  14402
      published_date:  {
        seconds:  1492352642
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  3
  value:  {
    video:  {
      video_id:  "_Dp8u97_rQ0"
      video_title:  "PR-003:Learning phrase representations using RNN encoder-decoder for statistical machine translation"
      number_of_likes:  34
      number_of_views:  6319
      published_date:  {
        seconds:  1495764575
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  4
  value:  {
    video:  {
      video_id:  "1jGr_OFyfa0"
      video_title:  "PR-004: Image Super-Resolution Using Deep Convolutional Networks"
      number_of_likes:  64
      number_of_views:  9817
      published_date:  {
        seconds:  1492956744
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  5
  value:  {
    video:  {
      video_id:  "V7_cNTfm2i8"
      video_title:  "PR-005: Playing Atari with Deep Reinforcement Learning (NIPS 2013 Deep Learning Workshop)"
      number_of_likes:  53
      number_of_views:  8180
      published_date:  {
        seconds:  1494165820
      }
      uploader:  "Sung Kim"
    }
  }
}
pr_id_to_video:  {
  key:  6
  value:  {
    video:  {
      video_id:  "2wbDiZCWQtY"
      video_title:  "PR-006: Neural Turing Machine"
      number_of_likes:  41
      number_of_views:  5051
      published_date:  {
        seconds:  1494447474
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  7
  value:  {
    video:  {
      video_id:  "YF6nLVDlznE"
      video_title:  "PR-007:  Deep Photo Style Transfer"
      number_of_likes:  29
      number_of_views:  5719
      published_date:  {
        seconds:  1494826006
      }
      uploader:  "Sung Kim"
    }
  }
}
pr_id_to_video:  {
  key:  8
  value:  {
    video:  {
      video_id:  "jbnjzyJDldA"
    }
  }
}
pr_id_to_video:  {
  key:  9
  value:  {
    video:  {
      video_id:  "tOItokBZSfU"
      video_title:  "PR-009: Distilling the Knowledge in a Neural Network (Slide: English, Speaking: Korean)"
      number_of_likes:  43
      number_of_views:  6455
      published_date:  {
        seconds:  1495514577
      }
      uploader:  "Choung young jae"
    }
  }
}
pr_id_to_video:  {
  key:  10
  value:  {
    video:  {
      video_id:  "KYA-GEhObIs"
      video_title:  "PR-010: Auto-Encoding Variational Bayes, ICLR 2014"
      number_of_likes:  202
      number_of_views:  12139
      published_date:  {
        seconds:  1495549847
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  11
  value:  {
    video:  {
      video_id:  "Rv3osRZWGbg"
      video_title:  "PR-011: Spatial Transformer Networks"
      number_of_likes:  45
      number_of_views:  5440
      published_date:  {
        seconds:  1495978512
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  12
  value:  {
    video:  {
      video_id:  "kcPAGIgBGRs"
      video_title:  "PR-012: Faster R-CNN : Towards Real-Time Object Detection with Region Proposal Networks"
      number_of_likes:  387
      number_of_views:  48639
      published_date:  {
        seconds:  1495981094
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  13
  value:  {
    video:  {
      video_id:  "n2J7giHrS-Y"
      video_title:  "PR-013: Domain Adversarial Training of Neural Network"
      number_of_likes:  51
      number_of_views:  5875
      published_date:  {
        seconds:  1496675287
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  14
  value:  {
    video:  {
      video_id:  "Y1loN3Sc4Dk"
      video_title:  "PR-014: On Human Motion Prediction using RNNs (2017)"
      number_of_likes:  53
      number_of_views:  5110
      published_date:  {
        seconds:  1496611967
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  15
  value:  {
    video:  {
      video_id:  "IRB2vXSet2E"
      video_title:  "PR-015:Convolutional Neural Networks for Sentence Classification"
      number_of_likes:  49
      number_of_views:  5780
      published_date:  {
        seconds:  1497187460
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  16
  value:  {
    video:  {
      video_id:  "eTDcoeqj1_w"
      video_title:  "PR-016: You only look once: Unified, real-time object detection"
      number_of_likes:  99
      number_of_views:  16119
      published_date:  {
        seconds:  1497795435
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  17
  value:  {
    video:  {
      video_id:  "XP3vyVrrt3Q"
      video_title:  "PR-017: Neural Architecture Search with Reinforcement Learning"
      number_of_likes:  31
      number_of_views:  3949
      published_date:  {
        seconds:  1497796191
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  18
  value:  {
    video:  {
      video_id:  "Lb1PVpFp9F8"
      video_title:  "PR-018: A Simple Neural Network Module for Relational Reasoning (DeepMind)"
      number_of_likes:  63
      number_of_views:  6765
      published_date:  {
        seconds:  1498432650
      }
      uploader:  "Sung Kim"
    }
  }
}
pr_id_to_video:  {
  key:  19
  value:  {
    video:  {
      video_id:  "h2WSVBAC1t4"
      video_title:  "PR-019: Continuous Control with Deep Reinforcement Learning"
      number_of_likes:  52
      number_of_views:  5324
      published_date:  {
        seconds:  1498452479
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  20
  value:  {
    video:  {
      video_id:  "absOinFeGv0"
      video_title:  "PR-020: Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification"
      number_of_likes:  14
      number_of_views:  1812
      published_date:  {
        seconds:  1499002058
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  21
  value:  {
    video:  {
      video_id:  "TDx8iZHwFtM"
      video_title:  "PR-021: Batch Normalization (language: korean)"
      number_of_likes:  103
      number_of_views:  8029
      published_date:  {
        seconds:  1499004604
      }
      uploader:  "Choung young jae"
    }
  }
}
pr_id_to_video:  {
  key:  22
  value:  {
    video:  {
      video_id:  "_4jbgniqt_Q"
      video_title:  "PR-022: InfoGAN (OpenAI)"
      number_of_likes:  42
      number_of_views:  5905
      published_date:  {
        seconds:  1499608297
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  23
  value:  {
    video:  {
      video_id:  "6fdclSGgeio"
      video_title:  "PR-023: YOLO9000: Better, Faster, Stronger"
      number_of_likes:  95
      number_of_views:  12502
      published_date:  {
        seconds:  1500299473
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  24
  value:  {
    video:  {
      video_id:  "BvcwEz4VPIQ"
      video_title:  "PR-024: Pixel Recurrent Neural Network"
      number_of_likes:  49
      number_of_views:  5536
      published_date:  {
        seconds:  1502156580
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  25
  value:  {
    video:  {
      video_id:  "KdRo7ATNs9g"
      video_title:  "PR-025: Learning with side information through modality hallucination (2016)"
      number_of_likes:  18
      number_of_views:  1823
      published_date:  {
        seconds:  1500818803
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  26
  value:  {
    video:  {
      video_id:  "ZdPBkPGfRSk"
      video_title:  "PR-026: Notes for CVPR Machine Learning Session"
      number_of_likes:  9
      number_of_views:  1502
      published_date:  {
        seconds:  1501469470
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  27
  value:  {
    video:  {
      video_id:  "uZ2GtEe-50E"
      video_title:  "PR-027:GloVe - Global vectors for word representation"
      number_of_likes:  65
      number_of_views:  4314
      published_date:  {
        seconds:  1502026123
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  28
  value:  {
    video:  {
      video_id:  "fe2Vn0mwALI"
      video_title:  "PR-028: Densely Connected Convolutional Networks (CVPR 2017, Best Paper Award) by Gao Huang et al."
      number_of_likes:  124
      number_of_views:  12472
      published_date:  {
        seconds:  1502159004
      }
      uploader:  "Sung Kim"
    }
  }
}
pr_id_to_video:  {
  key:  29
  value:  {
    video:  {
      video_id:  "AXi4s3aFN6M"
      video_title:  "PR-029: Apprenticeship Learning via Inverse Reinforcement Learning"
      number_of_likes:  17
      number_of_views:  2086
      published_date:  {
        seconds:  1505165154
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  30
  value:  {
    video:  {
      video_id:  "nGPMKnoJTcI"
      video_title:  "PR-030: Photo-Realistic Single Image Super Resolution Using a Generative Adversarial Network"
      number_of_likes:  24
      number_of_views:  2795
      published_date:  {
        seconds:  1502636018
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  31
  value:  {
    video:  {
      video_id:  "p55H46RiZ6k"
      video_title:  "PR-031: Learning to learn by gradient descent by gradient descent"
      number_of_likes:  16
      number_of_views:  2373
      published_date:  {
        seconds:  1504453983
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  32
  value:  {
    video:  {
      video_id:  "Q-Cm7nw85iE"
      video_title:  "PR-032: Deep Visual-Semantic Alignments for Generating Image Descriptions"
      number_of_likes:  13
      number_of_views:  2031
      published_date:  {
        seconds:  1504445734
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  33
  value:  {
    video:  {
      video_id:  "TYDGTnxUGHQ"
      video_title:  "PR-033: PVANet: Lightweight Deep Neural Networks for Real-time Object Detection"
      number_of_likes:  25
      number_of_views:  3381
      published_date:  {
        seconds:  1504446966
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  34
  value:  {
    video:  {
      video_id:  "V0dLhyg5_Dw"
      video_title:  "PR-034: Inception and Xception"
      number_of_likes:  79
      number_of_views:  10198
      published_date:  {
        seconds:  1505052461
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  35
  value:  {
    video:  {
      video_id:  "xlmlY8WHjkU"
      video_title:  "PR-035: Understanding Black-box Predictions via Influence Functions (2017)"
      number_of_likes:  26
      number_of_views:  3394
      published_date:  {
        seconds:  1505051523
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  36
  value:  {
    video:  {
      video_id:  "S_fbBYbXypc"
      video_title:  "PR-036: Learning to Remember Rare Events"
      number_of_likes:  7
      number_of_views:  1488
      published_date:  {
        seconds:  1505657142
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  37
  value:  {
    video:  {
      video_id:  "oxSrjuspQEs"
      video_title:  "PR-037: Ask me anything: Dynamic memory networks for natural language processing"
      number_of_likes:  24
      number_of_views:  2364
      published_date:  {
        seconds:  1505654553
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  38
  value:  {
    video:  {
      video_id:  "7hRO2bS810M"
      video_title:  "PR-038: Explaining and Harnessing Adversarial Examples"
      number_of_likes:  7
      number_of_views:  1540
      published_date:  {
        seconds:  1507170279
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  39
  value:  {
    video:  {
      video_id:  "aU91bDGmy7I"
      video_title:  "PR-039: Dropout as a Bayesian approximation"
      number_of_likes:  56
      number_of_views:  5080
      published_date:  {
        seconds:  1508076910
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  40
  value:  {
    video:  {
      video_id:  "GyQnex_DK2k"
      video_title:  "PR-040: WaveNet - A Generative Model for Raw Audio"
      number_of_likes:  63
      number_of_views:  7138
      published_date:  {
        seconds:  1508077701
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  41
  value:  {
    video:  {
      video_id:  "BrmCnoYhQb4"
      video_title:  "PR-041: Show and Tell: A Neural Image Caption Generator"
      number_of_likes:  26
      number_of_views:  4492
      published_date:  {
        seconds:  1508678893
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  42
  value:  {
    video:  {
      video_id:  "KN120w3PZIA"
      video_title:  "PR-042: Adam: A Method for Stochastic Optimization"
      number_of_likes:  39
      number_of_views:  4156
      published_date:  {
        seconds:  1508682336
      }
      uploader:  "Ji-Hoon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  43
  value:  {
    video:  {
      video_id:  "-tUQXSdEsMk"
      video_title:  "PR-043: HyperNetworks"
      number_of_likes:  13
      number_of_views:  1678
      published_date:  {
        seconds:  1509287449
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  44
  value:  {
    video:  {
      video_id:  "7UoOFKcyIvM"
      video_title:  "PR-044: MobileNet"
      number_of_likes:  140
      number_of_views:  14758
      published_date:  {
        seconds:  1509456696
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  45
  value:  {
    video:  {
      video_id:  "JiC78rUF4iI"
      video_title:  "PR-045: DeepLab: Semantic Image Segmentation"
      number_of_likes:  93
      number_of_views:  8708
      published_date:  {
        seconds:  1509896571
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  46
  value:  {
    video:  {
      video_id:  "8hdY6Jns5-k"
      video_title:  "PR-046: Deep Knowledge Tracing"
      number_of_views:  2013
      published_date:  {
        seconds:  1509893052
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  47
  value:  {
    video:  {
      video_id:  "-Z1NIzLxgRU"
      video_title:  "PR047: Learning Deep Features for Discriminative Localization"
      number_of_likes:  31
      number_of_views:  2216
      published_date:  {
        seconds:  1510500873
      }
      uploader:  "이광희"
    }
  }
}
pr_id_to_video:  {
  key:  48
  value:  {
    video:  {
      video_id:  "RlAgB0Ooxaw"
      video_title:  "PR-048: Towards Principled Methods for Training Generative Adversarial Networks"
      number_of_likes:  19
      number_of_views:  1703
      published_date:  {
        seconds:  1510652207
      }
      uploader:  "Ji-Hoon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  49
  value:  {
    video:  {
      video_id:  "6zGgVIlStXs"
      video_title:  "PR-049: Attention is All You Need"
      number_of_views:  7224
      published_date:  {
        seconds:  1512304902
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  50
  value:  {
    video:  {
      video_id:  "3cFfCM4CXws"
      video_title:  "PR-050: Convolutional LSTM Network: A Machine Learning Approach for Precipitation Nowcasting"
      number_of_likes:  38
      number_of_views:  6944
      published_date:  {
        seconds:  1511707163
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  51
  value:  {
    video:  {
      video_id:  "iCgT8G4PkqI"
      video_title:  "PR-051: Conditional Generative Adversarial Nets"
      number_of_likes:  24
      number_of_views:  3428
      published_date:  {
        seconds:  1512310569
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  52
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  53
  value:  {
    video:  {
      video_id:  "faGsrPX1yFM"
      video_title:  "PR-053: Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization"
      number_of_likes:  34
      number_of_views:  6457
      published_date:  {
        seconds:  1512915707
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  54
  value:  {
    video:  {
      video_id:  "pNuBdj53Hbc"
      video_title:  "PR-054: ShuffleNet: An Extremely Efficient Convolutional Neural Network for Mobile Devices"
      number_of_likes:  52
      number_of_views:  6165
      published_date:  {
        seconds:  1513005030
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  55
  value:  {
    video:  {
      video_id:  "upskBSbA9cA"
      video_title:  "PR-055: Neural Machine Translation by Jointly Learning to Align and Translate"
      number_of_likes:  27
      number_of_views:  2831
      published_date:  {
        seconds:  1513516897
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  56
  value:  {
    video:  {
      video_id:  "_YT_8CT2w_Q"
      video_title:  "PR-056: Capsule Network"
      number_of_likes:  67
      number_of_views:  5736
      published_date:  {
        seconds:  1513522378
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  57
  value:  {
    video:  {
      video_id:  "RtSZALC9DlU"
      video_title:  "PR-057: Mask R-CNN"
      number_of_likes:  133
      number_of_views:  10980
      published_date:  {
        seconds:  1515330928
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  58
  value:  {
    video:  {
      video_id:  "7fIAdhl0KYc"
      video_title:  "PR-058: The Consciousness Prior"
      number_of_views:  1150
      published_date:  {
        seconds:  1515333966
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  59
  value:  {
    video:  {
      video_id:  "w-P2V2LlrHg"
      video_title:  "PR-059: Style Transfer from Non-Parallel Text by Cross-Alignment"
      number_of_likes:  12
      number_of_views:  1050
      published_date:  {
        seconds:  1515977170
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  60
  value:  {
    video:  {
      video_id:  "V6zixdCIOqw"
      video_title:  "PR-060: Deep Neural Networks for YouTube Recommendations"
      number_of_likes:  49
      number_of_views:  4013
      published_date:  {
        seconds:  1516540254
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  61
  value:  {
    video:  {
      video_id:  "UxJNG7ENRNg"
      video_title:  "PR-061: Understanding Deep Learning Requires Rethinking Generalization"
      number_of_likes:  49
      number_of_views:  3235
      published_date:  {
        seconds:  1516543607
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  62
  value:  {
    video:  {
      video_id:  "6hg5d10SZr0"
      video_title:  "PR-062: Deep Learning: A Critical Appraisal (2018)"
      number_of_likes:  56
      number_of_views:  3615
      published_date:  {
        seconds:  1517147263
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  63
  value:  {
    video:  {
      video_id:  "ZO4bXgdcCQA"
      video_title:  "PR-063 Peephole: Predicting Network Performance Before Training"
      number_of_likes:  5
      number_of_views:  778
      published_date:  {
        seconds:  1517147277
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  64
  value:  {
    video:  {
      video_id:  "hKoJPqWLrI4"
      video_title:  "PR-064: Wide&Deep Learning for Recommender Systems"
      number_of_likes:  31
      number_of_views:  2139
      published_date:  {
        seconds:  1517749978
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  65
  value:  {
    video:  {
      video_id:  "_5ofbwltEKU"
      video_title:  "PR-065 : High-Resolution Image Synthesis and Semantic Manipulation with Conditional GANs"
      number_of_likes:  16
      number_of_views:  1891
      published_date:  {
        seconds:  1517753318
      }
      uploader:  "이광희"
    }
  }
}
pr_id_to_video:  {
  key:  66
  value:  {
    video:  {
      video_id:  "jFpO-E4RPhQ"
      video_title:  "PR-066: Don't decay the learning rate, increase the batch size"
      number_of_likes:  19
      number_of_views:  2359
      published_date:  {
        seconds:  1518357854
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  67
  value:  {
    video:  {
      video_id:  "iqN08EPMjSs"
      video_title:  "PR-067: Audio Super Resolution using Neural Nets"
      number_of_likes:  21
      number_of_views:  3366
      published_date:  {
        seconds:  1518357824
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  68
  value:  {
    video:  {
      video_id:  "okyo61ZZivA"
      video_title:  "PR-068: DeepAR: Probabilistic Forecasting with Autoregressive Recurrent Networks"
      number_of_likes:  23
      number_of_views:  3934
      published_date:  {
        seconds:  1519565309
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  69
  value:  {
    video:  {
      video_id:  "fbCcJaSQPPA"
      video_title:  "PR-069: Efficient Neural Architecture Search via Parameter Sharing"
      number_of_likes:  44
      number_of_views:  4294
      published_date:  {
        seconds:  1520088191
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  70
  value:  {
    video:  {
      video_id:  "CtaPFqq8P00"
      video_title:  "PR-070: SafetyNets: Verifiable Execution of Deep Neural Networks on an Untrusted Cloud"
      number_of_likes:  2
      number_of_views:  447
      published_date:  {
        seconds:  1520171150
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  71
  value:  {
    video:  {
      video_id:  "ty3SciyoIyk"
      video_title:  "PR-071: Categorical Reparameterization with Gumbel Softmax"
      number_of_likes:  41
      number_of_views:  4257
      published_date:  {
        seconds:  1520172922
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  72
  value:  {
    video:  {
      video_id:  "9mFZmpIbMDs"
      video_title:  "PR-072: Deep Compression"
      number_of_likes:  27
      number_of_views:  2162
      published_date:  {
        seconds:  1520777304
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  73
  value:  {
    video:  {
      video_id:  "U8IpNf1b57w"
      video_title:  "PR-073: Generative Semantic Manipulation with Contrasting GAN"
      number_of_likes:  4
      number_of_views:  757
      published_date:  {
        seconds:  1520778031
      }
      uploader:  "이광희"
    }
  }
}
pr_id_to_video:  {
  key:  74
  value:  {
    video:  {
      video_id:  "A1o6SUsWd98"
      video_title:  "PR-074: ObamaNet: Photo-realistic lip-sync from text"
      number_of_views:  2007
      published_date:  {
        seconds:  1521381942
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  75
  value:  {
    video:  {
      video_id:  "odNHEkfJAc4"
      video_title:  "PR-075: On Calibration of Modern Neural Networks (2017)"
      number_of_likes:  27
      number_of_views:  2882
      published_date:  {
        seconds:  1521987100
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  76
  value:  {
    video:  {
      video_id:  "NxKpgY6sWOQ"
      video_title:  "PR-076: Distributed Representations of Sentences and Documents"
      number_of_likes:  18
      number_of_views:  1744
      published_date:  {
        seconds:  1522587607
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  77
  value:  {
    video:  {
      video_id:  "BXODIP3QjJI"
      video_title:  "PR-077: SeqGAN: Sequence Generative Adversarial Nets with Policy Gradient"
      number_of_likes:  15
      number_of_views:  2082
      published_date:  {
        seconds:  1523239176
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  78
  value:  {
    video:  {
      video_id:  "btsZOMsyH_o"
      video_title:  "PR-078: Net2Net: Accelerating Learning via Knowledge Transfer"
      number_of_likes:  14
      number_of_views:  1001
      published_date:  {
        seconds:  1523878774
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  79
  value:  {
    video:  {
      video_id:  "UXVKSSXdwb8"
      video_title:  "PR-079: Synthesizing Audio with Generative Adversarial Networks"
      number_of_likes:  20
      number_of_views:  1302
      published_date:  {
        seconds:  1523206394
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  80
  value:  {
    video:  {
      video_id:  "MnHCe8tGjQ8"
      video_title:  "PR-080: Practical Bayesian Optimization of Machine Learning Algorithms"
      number_of_likes:  26
      number_of_views:  2377
      published_date:  {
        seconds:  1523799259
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  81
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  82
  value:  {
    video:  {
      video_id:  "OgNSFKeHy8k"
      video_title:  "PR-082: Introduction to Speech Separation"
      number_of_likes:  14
      number_of_views:  1210
      published_date:  {
        seconds:  1524410583
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  83
  value:  {
    video:  {
      video_id:  "ZM153wo3baA"
      video_title:  "PR-083: Non-local Neural Networks"
      number_of_likes:  45
      number_of_views:  4896
      published_date:  {
        seconds:  1525008094
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  84
  value:  {
    video:  {
      video_id:  "nkYFEoKQBH0"
      video_title:  "PR-084 MegDet: A Large Mini-Batch Object Detector (CVPR2018)"
      number_of_likes:  3
      number_of_views:  1222
      published_date:  {
        seconds:  1525663256
      }
      uploader:  "Taegyun Jeon"
    }
  }
}
pr_id_to_video:  {
  key:  85
  value:  {
    video:  {
      video_id:  "7WhWkhFAIO4"
      video_title:  "PR-085: In-Datacenter Performance Analysis of a Tensor Processing Unit"
      number_of_likes:  21
      number_of_views:  1584
      published_date:  {
        seconds:  1526140508
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  86
  value:  {
    video:  {
      video_id:  "fQtuWEuwXrA"
      video_title:  "PR-086: Curriculum Learning"
      number_of_likes:  5
      number_of_views:  1367
      published_date:  {
        seconds:  1526221428
      }
      uploader:  "차준범"
    }
  }
}
pr_id_to_video:  {
  key:  87
  value:  {
    video:  {
      video_id:  "iXSYqohGQhM"
      video_title:  "PR-087: Spectral Normalization for Generative Adversarial Networks"
      number_of_likes:  44
      number_of_views:  4659
      published_date:  {
        seconds:  1526221916
      }
      uploader:  "Jaejun Yoo"
    }
  }
}
pr_id_to_video:  {
  key:  88
  value:  {
    video:  {
      video_id:  "uM0rQtL6_AA"
      video_title:  "PR-088: Deep Variational Bayes Filters (2017)"
      number_of_likes:  37
      number_of_views:  2792
      published_date:  {
        seconds:  1526901682
      }
      uploader:  "Terry TaeWoong Um"
    }
  }
}
pr_id_to_video:  {
  key:  89
  value:  {
    video:  {
      video_id:  "5whGIpoLoq4"
      video_title:  "PR-089: Beyond Word Importance: Contextual Decomposition to Extract Interactions from LSTMs"
      number_of_views:  440
      published_date:  {
        seconds:  1528641922
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  90
  value:  {
    video:  {
      video_id:  "T7i_YKN2EY8"
      video_title:  "PR-090: Representation Learning by Learning to Count"
      number_of_likes:  3
      number_of_views:  426
      published_date:  {
        seconds:  1529233262
      }
      uploader:  "Suh Kiho"
    }
  }
}
pr_id_to_video:  {
  key:  91
  value:  {
    video:  {
      video_id:  "v1GbxpKqH8Q"
      video_title:  "PR-091: A Universal Music Translation Network"
      number_of_likes:  12
      number_of_views:  732
      published_date:  {
        seconds:  1529241765
      }
      uploader:  "Seungil Kim"
    }
  }
}
pr_id_to_video:  {
  key:  92
  value:  {
    video:  {
      video_id:  "pAH3KhVnADE"
      video_title:  "PR-092: Distributed Training of Neural Networks"
      number_of_likes:  4
      number_of_views:  745
      published_date:  {
        seconds:  1529243628
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  93
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  94
  value:  {
    video:  {
      video_id:  "fxJXXKZb-ik"
      video_title:  "PR-094: Model-Agnostic Meta-Learning for fast adaptation of deep networks"
      number_of_likes:  58
      number_of_views:  5060
      published_date:  {
        seconds:  1529847830
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  95
  value:  {
    video:  {
      video_id:  "dAGI3mlOmfw"
      video_title:  "PR-095: Modularity Matters:  Learning Invariant Relational Reasoning Tasks"
      number_of_likes:  9
      number_of_views:  767
      published_date:  {
        seconds:  1532272031
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  96
  value:  {
    video:  {
      video_id:  "WjUGrzBIDv0"
      video_title:  "PR-096: Taskonomy: Disentangling Task Transfer Learning"
      number_of_likes:  10
      number_of_views:  1179
      published_date:  {
        seconds:  1530451567
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  97
  value:  {
    video:  {
      video_id:  "l-pcG77Hr58"
      video_title:  "PR-097: Learning Representations for Counterfactual Inference"
      number_of_views:  819
      published_date:  {
        seconds:  1531061236
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  98
  value:  {
    video:  {
      video_id:  "tGbMWAFMMBQ"
      video_title:  "PR-098: MegaDepth: Learning Single-View Depth Prediction from Internet Photos (CVPR2018)"
      number_of_likes:  6
      number_of_views:  776
      published_date:  {
        seconds:  1531661811
      }
      uploader:  "이광희"
    }
  }
}
pr_id_to_video:  {
  key:  99
  value:  {
    video:  {
      video_id:  "cpCS7LBRkRU"
      video_title:  "PR-099: MRNet-Product2Vec"
      number_of_likes:  23
      number_of_views:  1342
      published_date:  {
        seconds:  1531661636
      }
      uploader:  "keun bong Kwak"
    }
  }
}
pr_id_to_video:  {
  key:  100
  value:  {
    video:  {
      video_id:  "ksTkCecBTCY"
      video_title:  "PR100: SeedNet"
      number_of_likes:  11
      number_of_views:  1043
      published_date:  {
        seconds:  1532265921
      }
      uploader:  "이광희"
    }
  }
}
pr_id_to_video:  {
  key:  101
  value:  {
    video:  {
      video_id:  "FfBp6xJqZVA"
      video_title:  "PR-101: Deep Feature Consistent Variational Autoencoder"
      number_of_likes:  34
      number_of_views:  9163
      published_date:  {
        seconds:  1536508427
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  102
  value:  {
    video:  {
      video_id:  "_onRnCb_h3Q"
      video_title:  "PR-102: Everybody Dance Now"
      number_of_views:  1365
      published_date:  {
        seconds:  1536505303
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  103
  value:  {
    video:  {
      video_id:  "zpJwm7f7EXs"
      video_title:  "PR-103: Visualizing Data using t-SNE"
      number_of_likes:  36
      number_of_views:  2870
      published_date:  {
        seconds:  1537108725
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  104
  value:  {
    video:  {
      video_id:  "WxeeqxqnRyE"
      video_title:  "PR-104: Video-to-Video synthesis"
      number_of_likes:  16
      number_of_views:  1607
      published_date:  {
        seconds:  1537107746
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  105
  value:  {
    video:  {
      video_id:  "4uDZxefPd-I"
      video_title:  "PR-105: MnasNet: Platform-Aware Neural Architecture Search for Mobile"
      number_of_likes:  23
      number_of_views:  1974
      published_date:  {
        seconds:  1538623331
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  106
  value:  {
    video:  {
      video_id:  "id_CmUaTWpg"
      video_title:  "PR-106: Learning to Explain: An Information-Theoretic Perspective on Model Interpretation"
      number_of_likes:  11
      number_of_views:  1138
      published_date:  {
        seconds:  1538321661
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  107
  value:  {
    video:  {
      video_id:  "BhZN6AqfylA"
      video_title:  "PR-107: Image Inpainting for Irregular Holes Using Partial Convolutions"
      number_of_likes:  26
      number_of_views:  2712
      published_date:  {
        seconds:  1539060135
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  108
  value:  {
    video:  {
      video_id:  "mT5Y-Zumbbw"
      video_title:  "PR-108: MobileNetV2: Inverted Residuals and Linear Bottlenecks"
      number_of_likes:  67
      number_of_views:  8198
      published_date:  {
        seconds:  1540388729
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  109
  value:  {
    video:  {
      video_id:  "1f0faOeqDQ0"
      video_title:  "PR-109: Large Scale GAN Training for High Fidelity Natural Image Synthesis"
      number_of_likes:  12
      number_of_views:  1205
      published_date:  {
        seconds:  1539797131
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  110
  value:  {
    video:  {
      video_id:  "nimHWHxjBJ8"
      video_title:  "PR-110: An Analysis of Scale Invariance in Object Detection – SNIP"
      number_of_likes:  14
      number_of_views:  1225
      published_date:  {
        seconds:  1540590955
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  111
  value:  {
    video:  {
      video_id:  "uwRz7PjVtB0"
      video_title:  "PR-111: EVA2:Exploiting Temporal Redundancy in Live Computer Vision"
      number_of_likes:  23
      number_of_views:  798
      published_date:  {
        seconds:  1540137553
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  112
  value:  {
    video:  {
      video_id:  "mLSPA76qSuU"
    }
  }
}
pr_id_to_video:  {
  key:  113
  value:  {
    video:  {
      video_id:  "6Yid4dituqo"
      video_title:  "PR-113: The Perception Distortion Tradeoff"
      number_of_likes:  16
      number_of_views:  1361
      published_date:  {
        seconds:  1540734798
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  114
  value:  {
    video:  {
      video_id:  "eMZXUqmp_PU"
      video_title:  "PR-114: Recycle-GAN, Unsupervised Video Retargeting"
      number_of_views:  1172
      published_date:  {
        seconds:  1540738223
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  115
  value:  {
    video:  {
      video_id:  "R0H0gqtnMyA"
      video_title:  "PR-115: Unsupervised Anomaly Detection with Generative Adversarial Networks"
      number_of_likes:  35
      number_of_views:  3269
      published_date:  {
        seconds:  1541343064
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  116
  value:  {
    video:  {
      video_id:  "6OVH1i2BVAE"
      video_title:  "PR-116: Glow: Generative Flow with Invertible 1x1 Convolutions"
      number_of_likes:  21
      number_of_views:  2791
      published_date:  {
        seconds:  1541342135
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  117
  value:  {
    video:  {
      video_id:  "VQsG_Yk9KuQ"
      video_title:  "PR-117: PeerNets: Exploiting Peer Wisdom Against Adversarial Attacks"
      number_of_likes:  6
      number_of_views:  769
      published_date:  {
        seconds:  1542016335
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  118
  value:  {
    video:  {
      video_id:  "AMPpOFtg3Q4"
      video_title:  "PR-118: Black-Box Attacks with Limited Queries and Information"
      number_of_likes:  2
      number_of_views:  419
      published_date:  {
        seconds:  1541943972
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  119
  value:  {
    video:  {
      video_id:  "3ROQis3hxPs"
      video_title:  "PR-119: Active Learning For Convolutional Neural Networks: A Core-Set Approach"
      number_of_likes:  22
      number_of_views:  1882
      published_date:  {
        seconds:  1543402308
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  120
  value:  {
    video:  {
      video_id:  "lrU6uXiJ_9Y"
      video_title:  "PR-120: ShuffleNet V2: Practical Guidelines for Efficient CNN Architecture Design"
      number_of_likes:  34
      number_of_views:  2881
      published_date:  {
        seconds:  1542552935
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  121
  value:  {
    video:  {
      video_id:  "GK4IO3qOnLc"
      video_title:  "PR-121: BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding"
      number_of_likes:  41
      number_of_views:  2830
      published_date:  {
        seconds:  1543981172
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  122
  value:  {
    video:  {
      video_id:  "TB7izZIWYyw"
      video_title:  "PR-122: CAN: Creative Adversarial Networks"
      number_of_likes:  13
      number_of_views:  1126
      published_date:  {
        seconds:  1543554496
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  123
  value:  {
    video:  {
      video_id:  "IKHzc7sGCxQ"
      video_title:  "PR-123: Partial Convolution based Padding"
      number_of_likes:  50
      number_of_views:  2265
      published_date:  {
        seconds:  1544173387
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  124
  value:  {
    video:  {
      video_id:  "saJcr74ldvs"
    }
  }
}
pr_id_to_video:  {
  key:  125
  value:  {
    video:  {
      video_id:  "8PoewOpK6b4"
      video_title:  "PR-125: ENERGY-BASED GENERATIVE ADVERSARIAL NETWORKS"
      number_of_likes:  7
      number_of_views:  707
      published_date:  {
        seconds:  1544368518
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  126
  value:  {
    video:  {
      video_id:  "-bvMCbk_FT8"
      video_title:  "PR-126: DensePose: Dense Human Pose Estimation In The Wild"
      number_of_views:  1783
      published_date:  {
        seconds:  1544365241
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  127
  value:  {
    video:  {
      video_id:  "0k3X-9y_9S8"
      video_title:  "PR-127: FaceNet"
      number_of_likes:  58
      number_of_views:  4047
      published_date:  {
        seconds:  1544971153
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  128
  value:  {
    video:  {
      video_id:  "5eofa6SksKU"
      video_title:  "PR-128: TimbreTron: A Wavenet(CycleGAN(CQT(Audio))) pipeline for musical timbre transfer"
      number_of_likes:  6
      number_of_views:  548
      published_date:  {
        seconds:  1544973323
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  129
  value:  {
    video:  {
      video_id:  "8zQECRiONAo"
      video_title:  "PR-129: Horovod: fast and easy distributed deep learning in TensorFlow"
      number_of_likes:  9
      number_of_views:  715
      published_date:  {
        seconds:  1546077765
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  130
  value:  {
    video:  {
      video_id:  "XHmRsgFrCTM"
      video_title:  "PR-130: Generative Adversarial Imitation Learning"
      number_of_likes:  14
      number_of_views:  2558
      published_date:  {
        seconds:  1545573404
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  131
  value:  {
    video:  {
      video_id:  "TWzEbMrH59o"
      video_title:  "PR-131: A Style-Based Generator Architecture for Generative Adversarial Networks"
      number_of_likes:  64
      number_of_views:  3880
      published_date:  {
        seconds:  1546903803
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  132
  value:  {
    video:  {
      video_id:  "ej1ISEoAK5g"
      video_title:  "PR-132: SSD: Single Shot MultiBox Detector"
      number_of_likes:  118
      number_of_views:  10394
      published_date:  {
        seconds:  1546786878
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  133
  value:  {
    video:  {
      video_id:  "g3McZgloCJo"
      video_title:  "PR-133: Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour"
      number_of_likes:  9
      number_of_views:  652
      published_date:  {
        seconds:  1547454308
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  134
  value:  {
    video:  {
      video_id:  "hiN0IMM50FM"
      video_title:  "PR-134 How Does Batch Normalization Help Optimization?"
      number_of_likes:  14
      number_of_views:  1000
      published_date:  {
        seconds:  1548117640
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  135
  value:  {
    video:  {
      video_id:  "LSlBoNNbULg"
      video_title:  "PR-135: Photo Wake-Up: 3D Character Animation from a Single Photo"
      number_of_likes:  55
      number_of_views:  2976
      published_date:  {
        seconds:  1548003936
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  136
  value:  {
    video:  {
      video_id:  "_wpDP-6afM4"
      video_title:  "PR-136 Self-Supervised Generative Adversarial Networks"
      number_of_likes:  23
      number_of_views:  1085
      published_date:  {
        seconds:  1547995361
      }
      uploader:  "강민국"
    }
  }
}
pr_id_to_video:  {
  key:  137
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  138
  value:  {
    video:  {
      video_id:  "VORJQQUphuw"
      video_title:  "PR-138: Mixture Density Network"
      number_of_views:  2381
      published_date:  {
        seconds:  1548599784
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  139
  value:  {
    video:  {
      video_id:  "dv5yUl6Lw1g"
      video_title:  "PR-139: Fully Convolutional Siamese Networks for Object Tracking"
      number_of_likes:  38
      number_of_views:  2845
      published_date:  {
        seconds:  1549845265
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  140
  value:  {
    video:  {
      video_id:  "_2l2UFIF08Q"
      video_title:  "PR-140:  Training Set Debugging Using Trusted Items"
      number_of_likes:  5
      number_of_views:  613
      published_date:  {
        seconds:  1549810486
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  141
  value:  {
    video:  {
      video_id:  "ltlhQXHGzgE"
      video_title:  "PR-141:  Auto-DeepLab: Hierarchical Neural Architecture Search for Semantic Image Segmentation"
      number_of_likes:  19
      number_of_views:  1693
      published_date:  {
        seconds:  1550413961
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  142
  value:  {
    video:  {
      video_id:  "tKQwlf-DAl0"
      video_title:  "PR-142: Wasserstein GAN"
      number_of_likes:  34
      number_of_views:  1979
      published_date:  {
        seconds:  1550412193
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  143
  value:  {
    video:  {
      video_id:  "APjGjwBR6o8"
      video_title:  "PR-143: Recurrent World Models Facilitate Policy Evolution"
      number_of_likes:  8
      number_of_views:  550
      published_date:  {
        seconds:  1551026446
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  144
  value:  {
    video:  {
      video_id:  "WReWeADJ3Pw"
      video_title:  "PR-144: SqueezeNext: Hardware-Aware Neural Network Design"
      number_of_likes:  33
      number_of_views:  2014
      published_date:  {
        seconds:  1551018415
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  145
  value:  {
    video:  {
      video_id:  "f5zULULWUwM"
      video_title:  "PR-145: Language Models are Unsupervised Multitask Learners (OpenAI GPT-2)"
      number_of_likes:  13
      number_of_views:  965
      published_date:  {
        seconds:  1552226192
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  146
  value:  {
    video:  {
      video_id:  "6OYmOtivQY8"
      video_title:  "PR-146: CornerNet: Detecting Objects as Paired Keypoints"
      number_of_likes:  24
      number_of_views:  1871
      published_date:  {
        seconds:  1570081370
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  147
  value:  {
    video:  {
      video_id:  "7lyxexSjshc"
      video_title:  "PR-147: Learning Deep Structure-Preserving Image-Text Embeddings"
      number_of_likes:  20
      number_of_views:  576
      published_date:  {
        seconds:  1552667121
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  148
  value:  {
    video:  {
      video_id:  "TgJuUxtLO3s"
      video_title:  "PR-148 deep anomaly detection using geometric transformations"
      number_of_likes:  25
      number_of_views:  1627
      published_date:  {
        seconds:  1552831505
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  149
  value:  {
    video:  {
      video_id:  "OKDaGzeUz4U"
      video_title:  "PR-149: Perceptual Losses for Real-Time Style Transfer and Super-Resolution"
      number_of_views:  2115
      published_date:  {
        seconds:  1552832996
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  150
  value:  {
    video:  {
      video_id:  "oBapZTL8LsE"
      video_title:  "PR-150: ImageNet-trained CNNs are Biased Towards Textures"
      number_of_likes:  17
      number_of_views:  1109
      published_date:  {
        seconds:  1553435404
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  151
  value:  {
    video:  {
      video_id:  "VDeJFb5jt5M"
      video_title:  "PR-151: The Unreasonable Effectiveness of Deep Features as a Perceptual Metric"
      number_of_likes:  6
      number_of_views:  714
      published_date:  {
        seconds:  1553438571
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  152
  value:  {
    video:  {
      video_id:  "i3-rTEFpyv0"
      video_title:  "PR-152:StarGAN: Unified Generative Adversarial Networks for Multi-Domain Image-to-Image Translation"
      number_of_likes:  21
      number_of_views:  1591
      published_date:  {
        seconds:  1554040628
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  153
  value:  {
    video:  {
      video_id:  "zGrwpa5-_0Y"
      video_title:  "PR-153: SNAIL: A Simple Neural Attentive Meta-Learner"
      number_of_likes:  11
      number_of_views:  921
      published_date:  {
        seconds:  1554043097
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  154
  value:  {
    video:  {
      video_id:  "1nJf35TSYtE"
      video_title:  "PR-154: Semantic Image Synthesis with Spatially-Adaptive Normalization"
      number_of_likes:  19
      number_of_views:  1467
      published_date:  {
        seconds:  1554651283
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  155
  value:  {
    video:  {
      video_id:  "qnGm1h365tc"
      video_title:  "PR-155: Exploring Randomly Wired Neural Networks for Image Recognition"
      number_of_likes:  92
      number_of_views:  4138
      published_date:  {
        seconds:  1554649684
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  156
  value:  {
    video:  {
      video_id:  "oZbKWOBfNhk"
      video_title:  "PR-156: ChannelNets: Compact and Efficient CNN via Channel-Wise Convolutions"
      number_of_likes:  1
      number_of_views:  222
      published_date:  {
        seconds:  1565744830
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  157
  value:  {
    video:  {
      video_id:  "JbXdn44myP4"
      video_title:  "PR-157: Best of both worlds: human-machine collaboration for object annotation"
      number_of_views:  349
      published_date:  {
        seconds:  1556532811
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  158
  value:  {
    video:  {
      video_id:  "hOFViMbYnrs"
      video_title:  "PR-158: FOTS: Fast Oriented Text Spotting with a Unified Network"
      number_of_likes:  25
      number_of_views:  990
      published_date:  {
        seconds:  1556529052
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  159
  value:  {
    video:  {
      video_id:  "sR7hBJGpwQo"
      video_title:  "PR-159: SIFA: Towards Cross- Modality Domain Adaptation for Medical Image Segmentation"
      number_of_likes:  10
      number_of_views:  476
      published_date:  {
        seconds:  1557132628
      }
      uploader:  "Sunghoon Joo"
    }
  }
}
pr_id_to_video:  {
  key:  160
  value:  {
    video:  {
      video_id:  "V9KusGzsx10"
      video_title:  "PR-160: GLoMo Unsupervised Learning of Transferable Relational Graph"
      number_of_likes:  13
      number_of_views:  622
      published_date:  {
        seconds:  1557076158
      }
      uploader:  "Doyup Lee"
    }
  }
}
pr_id_to_video:  {
  key:  161
  value:  {
    video:  {
      video_id:  "lSTljZy8ag4"
      video_title:  "PR-161: Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context"
      number_of_likes:  36
      number_of_views:  2217
      published_date:  {
        seconds:  1557744220
      }
      uploader:  "박성남"
    }
  }
}
pr_id_to_video:  {
  key:  162
  value:  {
    video:  {
      video_id:  "AqStpR29lTA"
      video_title:  "PR-162: DeepPermNet: Visual Permutation Learning"
      number_of_likes:  2
      number_of_views:  311
      published_date:  {
        seconds:  1557675917
      }
      uploader:  "강민국"
    }
  }
}
pr_id_to_video:  {
  key:  163
  value:  {
    video:  {
      video_id:  "Dvi5_YC8Yts"
      video_title:  "PR-163: CNN Attention Networks"
      number_of_likes:  125
      number_of_views:  8258
      published_date:  {
        seconds:  1558274434
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  164
  value:  {
    video:  {
      video_id:  "29QcXLoYC60"
      video_title:  "PR-164: InfoVAE: Balancing Learning and Inference in Variational Autoencoders"
      number_of_views:  593
      published_date:  {
        seconds:  1558883112
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  165
  value:  {
    video:  {
      video_id:  "4pY_6VG4npc"
      video_title:  "PR-165: Few-Shot Adversarial Learning of Realistic Neural Talking Head Models"
      number_of_likes:  40
      number_of_views:  2878
      published_date:  {
        seconds:  1558879643
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  166
  value:  {
    video:  {
      video_id:  "FAAt0jejWOA"
      video_title:  "PR-166: NAS-FPN: Learning Scalable Feature Pyramid Architecture for Object Detection"
      number_of_likes:  15
      number_of_views:  2115
      published_date:  {
        seconds:  1560917270
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  167
  value:  {
    video:  {
      video_id:  "-y0oghbEHMM"
      video_title:  "PR-167: Interpretability Beyond Feature Attribution: Testing with Concept Activation Vector (TCAV)"
      number_of_likes:  4
      number_of_views:  767
      published_date:  {
        seconds:  1559486974
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  168
  value:  {
    video:  {
      video_id:  "ANwAhuOeaiE"
      video_title:  "PR-168: Few Shot Unsupervised Image to Image Translation"
      number_of_likes:  11
      number_of_views:  895
      published_date:  {
        seconds:  1560267339
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  169
  value:  {
    video:  {
      video_id:  "Vhz0quyvR7I"
      video_title:  "PR-169: EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks"
      number_of_likes:  99
      number_of_views:  6325
      published_date:  {
        seconds:  1560496231
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  170
  value:  {
    video:  {
      video_id:  "7fSgqlC7Wdo"
      video_title:  "PR-170: ResNet - Deep Residual Learning for Image Recognition"
      number_of_likes:  16
      number_of_views:  1727
      published_date:  {
        seconds:  1565744287
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  171
  value:  {
    video:  {
      video_id:  "7TugLIfExKM"
      video_title:  "PR-171: Large margin softmax loss for Convolutional Neural Networks"
      number_of_likes:  4
      number_of_views:  1049
      published_date:  {
        seconds:  1561534996
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  172
  value:  {
    video:  {
      video_id:  "ENZBhDx0kqM"
      video_title:  "PR-172: Generalized Intersection over Union: A Metric and A Loss for Bounding Box Regression"
      number_of_likes:  30
      number_of_views:  1821
      published_date:  {
        seconds:  1561353991
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  173
  value:  {
    video:  {
      video_id:  "hk4e8ZCkNWg"
      video_title:  "PR-173 : Automatic Chemical Design Using a Data-Driven Continuous Representation of Molecules"
      number_of_likes:  10
      number_of_views:  389
      published_date:  {
        seconds:  1561309066
      }
      uploader:  "Sunghoon Joo"
    }
  }
}
pr_id_to_video:  {
  key:  174
  value:  {
    video:  {
      video_id:  "yqFDyX4ErSI"
      video_title:  "PR-174: Restricted Boltzmann Machine and Deep Belief Networks"
      number_of_likes:  12
      number_of_views:  977
      published_date:  {
        seconds:  1561903626
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  175
  value:  {
    video:  {
      video_id:  "koj9BKiu1rU"
      video_title:  "PR-175: XLNet: Generalized Autoregressive Pretraining for Language Understanding"
      number_of_likes:  55
      number_of_views:  2413
      published_date:  {
        seconds:  1561964703
      }
      uploader:  "박성남"
    }
  }
}
pr_id_to_video:  {
  key:  176
  value:  {
    video:  {
      video_id:  "ihbEF6WGlrA"
      video_title:  "PR-176: Combating Label Noise in Deep Learning using Abstention"
      number_of_likes:  18
      number_of_views:  897
      published_date:  {
        seconds:  1562509657
      }
      uploader:  "Doyup Lee"
    }
  }
}
pr_id_to_video:  {
  key:  177
  value:  {
    video:  {
      video_id:  "KSJcQlEKI0Q"
      video_title:  "PR-177: Framing U-Net via Deep Convolutional Framelets"
      number_of_views:  584
      published_date:  {
        seconds:  1562511247
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  178
  value:  {
    video:  {
      video_id:  "uqBsvoOY8jM"
      video_title:  "PR-178: Graph Convolutional Network"
      number_of_likes:  95
      number_of_views:  6055
      published_date:  {
        seconds:  1563112484
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  179
  value:  {
    video:  {
      video_id:  "CpRGaFPIZnw"
      video_title:  "PR-179: M3D-GAN: Multi-Modal Multi-Domain Translation with Universal Attention"
      number_of_likes:  8
      number_of_views:  558
      published_date:  {
        seconds:  1563115146
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  180
  value:  {
    video:  {
      video_id:  "dkNmYu610r8"
      video_title:  "PR-180: The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks"
      number_of_likes:  11
      number_of_views:  758
      published_date:  {
        seconds:  1564043119
      }
      uploader:  "Taekmin Kim"
    }
  }
}
pr_id_to_video:  {
  key:  181
  value:  {
    video:  {
      video_id:  "YdCXbBDuVuE"
      video_title:  "PR-181: Data Shapley: Equitable Valuation of Data for Machine Learning"
      number_of_likes:  7
      number_of_views:  534
      published_date:  {
        seconds:  1563717023
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  182
  value:  {
    video:  {
      video_id:  "twhZ3j_VCa0"
      video_title:  "PR-182: Deep Learning Ensemble Method"
      number_of_likes:  15
      number_of_views:  775
      published_date:  {
        seconds:  1564898851
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  183
  value:  {
    video:  {
      video_id:  "252YxqpHzsg"
      video_title:  "PR-183: MixNet: Mixed Depthwise Convolutional Kernels"
      number_of_likes:  28
      number_of_views:  1679
      published_date:  {
        seconds:  1564326548
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  184
  value:  {
    video:  {
      video_id:  "FPLvzxH8geY"
      video_title:  "PR-184: And the Bit Goes Down: Revisiting the Quantization of Neural Networks"
      number_of_likes:  7
      number_of_views:  530
      published_date:  {
        seconds:  1564926928
      }
      uploader:  "Young Seok Kim"
    }
  }
}
pr_id_to_video:  {
  key:  185
  value:  {
    video:  {
      video_id:  "DkcHEnxkXpM"
      video_title:  "PR-185: RetinaFace: Single-stage Dense Face Localisation in the Wild"
      number_of_likes:  25
      number_of_views:  2395
      published_date:  {
        seconds:  1570081394
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  186
  value:  {
    video:  {
      video_id:  "16BGnsIyh6M"
      video_title:  "PR-186: Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization"
      number_of_likes:  23
      number_of_views:  821
      published_date:  {
        seconds:  1565608448
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  187
  value:  {
    video:  {
      video_id:  "vUNAJsO2G98"
      video_title:  "PR-187 : MorphNet: Fast & Simple Resource-Constrained Structure Learning of Deep Networks"
      number_of_likes:  4
      number_of_views:  506
      published_date:  {
        seconds:  1565712056
      }
      uploader:  "Sunghoon Joo"
    }
  }
}
pr_id_to_video:  {
  key:  188
  value:  {
    video:  {
      video_id:  "vUNAJsO2G98"
      video_title:  "PR-187 : MorphNet: Fast & Simple Resource-Constrained Structure Learning of Deep Networks"
      number_of_likes:  4
      number_of_views:  506
      published_date:  {
        seconds:  1565712056
      }
      uploader:  "Sunghoon Joo"
    }
  }
}
pr_id_to_video:  {
  key:  189
  value:  {
    video:  {
      video_id:  "YiKn93Ud4dA"
      video_title:  "PR-189: Unsupervised Data Augmentation for Consistency Training"
      number_of_likes:  17
      number_of_views:  1174
      published_date:  {
        seconds:  1566745737
      }
      uploader:  "박성남"
    }
  }
}
pr_id_to_video:  {
  key:  190
  value:  {
    video:  {
      video_id:  "xaABseUoHAI"
      video_title:  "PR-190: A Baseline For Detecting Misclassified and Out-of-Distribution  Examples In Neural Networks"
      number_of_likes:  10
      number_of_views:  1045
      published_date:  {
        seconds:  1569764236
      }
      uploader:  "MinGuk Kang"
    }
  }
}
pr_id_to_video:  {
  key:  191
  value:  {
    video:  {
      video_id:  "cgolskL-_WM"
      video_title:  "PR-191: Learning Adversarially Fair and Transferable Representations"
      number_of_views:  379
      published_date:  {
        seconds:  1567348971
      }
      uploader:  "Byung-Hak Kim"
    }
  }
}
pr_id_to_video:  {
  key:  192
  value:  {
    video:  {
      video_id:  "9uNFtnRa_JU"
      video_title:  "PR-192: MoCoGAN: Decomposing Motion and Content for Video Generation"
      number_of_likes:  9
      number_of_views:  1222
      published_date:  {
        seconds:  1568189938
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  193
  value:  {
    video:  {
      video_id:  "3KoqN_yYhmI"
      video_title:  "PR-193: NISP: Pruning Networks using Neural Importance Score Propagation"
      number_of_likes:  10
      number_of_views:  566
      published_date:  {
        seconds:  1567953078
      }
      uploader:  "taesu"
    }
  }
}
pr_id_to_video:  {
  key:  194
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  195
  value:  {
    video:  {
      video_id:  "ud863JQmUW0"
      video_title:  "PR-195: MixMatch: A Holistic Approach to Semi-Supervised Learning"
      number_of_likes:  21
      number_of_views:  1419
      published_date:  {
        seconds:  1569160250
      }
      uploader:  "Jinsung Yoon"
    }
  }
}
pr_id_to_video:  {
  key:  196
  value:  {
    video:  {
      video_id:  "6hadVw4Sy2M"
      video_title:  "PR-196: Stand Alone Self Attention in Vision Models"
      number_of_likes:  9
      number_of_views:  1557
      published_date:  {
        seconds:  1571072079
      }
      uploader:  "정지원"
    }
  }
}
pr_id_to_video:  {
  key:  197
  value:  {
    video:  {
      video_id:  "YmTNpF2OOjA"
      video_title:  "PR-197: One ticket to win them all: generalizing lottery ticket initialization"
      number_of_likes:  21
      number_of_views:  1013
      published_date:  {
        seconds:  1569769625
      }
      uploader:  "JinWon Lee"
    }
  }
}
pr_id_to_video:  {
  key:  198
  value:  {
    video:  {}
  }
}
pr_id_to_video:  {
  key:  199
  value:  {
    video:  {
      video_id:  "EkndN7svgUk"
      video_title:  "PR-199: SNIPER:Efficient Multi Scale Training"
      number_of_likes:  16
      number_of_views:  1384
      published_date:  {
        seconds:  1570377571
      }
      uploader:  "visionNoob"
    }
  }
}
pr_id_to_video:  {
  key:  200
  value:  {
    video:  {
      video_id:  "BHEncY-f548"
      video_title:  "PR-200: Online Model Distillation for Efficient Video Inference"
      number_of_likes:  16
      number_of_views:  713
      published_date:  {
        seconds:  1571035103
      }
      uploader:  "Soyeon Kim"
    }
  }
}
pr_id_to_video:  {
  key:  201
  value:  {
    video:  {
      video_id:  "D-baIgejA4M"
      video_title:  "PR-201: Bag of Tricks for Image Classification with Convolutional Neural Networks"
      number_of_likes:  47
      number_of_views:  8745
      published_date:  {
        seconds:  1571580127
      }
      uploader:  "Jiyang Kang"
    }
  }
}
pr_id_to_video:  {
  key:  202
  value:  {
    video:  {
      video_id:  "iR7T3lH20gI"
      video_title:  "PR-202: Modeling Task Relationships in Multi-task Learning with Multi-gate Mixture-of-Experts"
      number_of_likes:  14
      number_of_views:  1043
      published_date:  {
        seconds:  1571582247
      }
      uploader:  "박성남"
    }
  }
}
pr_id_to_video:  {
  key:  203
  value:  {
    video:  {
      video_id:  "3hL0uVtJrXM"
      video_title:  "PR-203 : Class-Balanced Loss Based on Effective Number of Samples"
      number_of_likes:  15
      number_of_views:  1268
      published_date:  {
        seconds:  1572183724
      }
      uploader:  "Sunghoon Joo"
    }
  }
}
pr_id_to_video:  {
  key:  204
  value:  {
    video:  {
      video_id:  "YNicvevmByo"
      video_title:  "PR-204: Learning deep representations by mutual information estimation and maximization"
      number_of_likes:  30
      number_of_views:  2470
      published_date:  {
        seconds:  1572789342
      }
      uploader:  "SeongOk Ryu"
    }
  }
}
pr_id_to_video:  {
  key:  205
  value:  {
    video:  {
      video_id:  "yyqZ1K5u2_8"
      video_title:  "PR-205: A Closer Look at Few Shot Classification"
      number_of_likes:  26
      number_of_views:  2134
      published_date:  {
        seconds:  1573496397
      }
      uploader:  "Taeoh Kim"
    }
  }
}
pr_id_to_video:  {
  key:  206
  value:  {
    video:  {
      video_id:  "sFN_EgCsNzM"
      video_title:  "PR-206: PointRCNN: 3D Object Proposal Generation and Detection from Point Cloud"
      number_of_likes:  38
      number_of_views:  2730
      published_date:  {
        seconds:  1573396201
      }
      uploader:  "Doyup Lee"
    }
  }
}
pr_id_to_video:  {
  key:  207
  value:  {
    video:  {
      video_id:  "HMgcvgRrDcA"
      video_title:  "PR-207: YOLOv3: An Incremental Improvement"
      number_of_likes:  116
      number_of_views:  7247
      published_date:  {
        seconds:  1574001134
      }
      uploader:  "JinWon Lee"
    }
  }
}
