name: Docker Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - run: cd server && go test -v --race ./...

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      # Whether a new release was published (true or false)
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      # Version of the new release. (e.g. 1.3.0)
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      # Major version of the new release. (e.g. 1)
      new_release_major_version: ${{ steps.semantic.outputs.new_release_major_version }}
      # Minor version of the new release. (e.g. 3)
      new_release_minor_version: ${{ steps.semantic.outputs.new_release_minor_version }}
      # Patch version of the new release. (e.g. 0)
      new_release_patch_version: ${{ steps.semantic.outputs.new_release_patch_version }}
      # The distribution channel on which the last release was initially made available (undefined for the default distribution channel).
      new_release_channel: ${{ steps.semantic.outputs.new_release_channel }}
      # The release notes for the new release.
      new_release_notes: ${{ steps.semantic.outputs.new_release_notes }}

    steps:
      - uses: actions/checkout@v2
      - uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest

    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/codingpot/pr12er
          tags: |
            type=raw,value=${{ needs.release.outputs.new_release_major_version }}
            type=raw,value=${{ needs.release.outputs.new_release_major_version }}.${{ needs.release.outputs.new_release_minor_version }}
            type=raw,value=${{ needs.release.outputs.new_release_version }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/deploy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
