name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  workflow_run:
    workflows:
      - Generate Database
    types:
      - completed
jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk

  go-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: server
          version: v1.42
      - run: go test -v --race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go build -o server cmd/server/main.go
      - run: go build -o client cmd/client/main.go
      - run: bash <(curl -s https://codecov.io/bash) -F server

  dbctl-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbctl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: dbctl
      - run: go test -v --race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go build main.go
      - run: bash <(curl -s https://codecov.io/bash) -F dbctl

  deploy-to-okteto:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs:
      - go-build

    steps:
      - uses: actions/checkout@v2
      - uses: okteto/login@master
        with:
          token: ${{ secrets.KKWEON_OKTETO_TOKEN }}

      - uses: okteto/namespace@master
        with:
          namespace: kkweon

      - uses: okteto/pipeline@master
        with:
          name: test-1234

  deploy-to-gh-pages:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs:
      - flutter-build

    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web --release
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./client/build/web
