name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk

  go-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - run: go test -v --race ./...
      - run: go build -o server cmd/server/main.go
      - run: go build -o client cmd/client/main.go

  deploy-to-raspberry:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs:
      - go-build

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_KKWEON_USERNAME }}
          password: ${{ secrets.DOCKER_KKWEON_PASSWORD }}

      - shell: bash
        run: echo "${{ secrets.KKWEON_RASPBERRY_KUBECONFIG }}" > ./kubeconfig

      - uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
          kube-context: raspberry
          kubeconfig: ./kubeconfig
