name: Discord Notification

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: "Ilshidur/action-discord@0.3.0"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ github.event_name == 'pull_request' }}
        with:
          args: |-
            A new PR {{ EVENT_PAYLOAD.pull_request.title }}

            by {{ EVENT_PAYLOAD.sender.login}}

            at {{ EVENT_PAYLOAD.pull_request.html_url }}
      - uses: "Ilshidur/action-discord@0.3.0"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ github.event_name == 'issues' }}
        with:
          args: |-
            A new issue {{ EVENT_PAYLOAD.issue.title }}

            by {{ EVENT_PAYLOAD.sender.login}}

            at {{ EVENT_PAYLOAD.issue.html_url }}
