name: Discord Notification

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - ready_for_review

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: "Ilshidur/action-discord@0.3.0"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: >-
            ${{ github.event_name }} was created at

            ```json
            {{ EVENT_PAYLOAD }}
            ```
