# Test protoc generate
name: Protoc

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - run: make install gen.all
      - run: buf lint
      - run: |
          git update-index --refresh
          git diff-index --quiet HEAD -- || { git diff HEAD && echo "::warning::there's diff in generated files. Check your protoc versions."; }
