name: Docker Release for Tools

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "client/pubspec.*"
      - "server/go.*"
      - "tools/Dockerfile"
      - "Makefile"
  push:
    branches:
      - main
    paths:
      - "client/pubspec.*"
      - "server/go.*"
      - "tools/Dockerfile"
      - "Makefile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: codingpot/buf
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_KKWEON_USERNAME }}
          password: ${{ secrets.DOCKER_KKWEON_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tools/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
